#ifndef THEME_H
#define THEME_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

#define THEME_BG 0xF4F6FAu
#define THEME_SURFACE 0xFFFFFFu
#define THEME_SURFACE_2 0xEEF1F6u
#define THEME_ACCENT 0x3D8BFFu
#define THEME_OK 0x34C759u
#define THEME_WARN 0xFF9F0Au
#define THEME_ERR 0xFF3B30u
#define THEME_TEXT 0x1A2030u
#define THEME_MUTED 0x6B7385u
#define THEME_HAIRLINE 0xE1E5EEu
#define THEME_TILE_FILES 0x3D8BFFu
#define THEME_TILE_HOME 0x34C759u
#define THEME_TILE_GAME 0xFF9F0Au
#define THEME_TILE_MUSIC 0xAF52DEu
#define THEME_TILE_NET 0x32ADE6u
#define THEME_TILE_SET 0xFF6482u

#define THEME_HIT_MIN_PX 40
#define THEME_ROW_H 44
#define THEME_STATUS_H 32
#define THEME_NOWPLAYING_H 36
#define THEME_APPBAR_H 40
#define THEME_RADIUS_PX 8
#define THEME_TILE_RADIUS_PX 16
#define THEME_PANEL_W 480
#define THEME_PANEL_H 272
#define THEME_CONTENT_H (THEME_PANEL_H - THEME_STATUS_H)

#ifdef __cplusplus
}
#endif

#endif /* THEME_H */
